### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by Gobot1234** [Gobot1234/steam-ext-dota2#1]
- [x] Set up protobufs and base framework.
- [ ] SO messages see https://github.com/Gobot1234/steam-ext-tf2/blob/master/steam/ext/tf2/state.py#L143-L258 for a framework and https://github.com/ValvePython/dota2/blob/master/dota2/features/sharedobjects.py for what to implment.
- [ ] Features like chat and messaging guilds etc.
